# Generated by Django 2.0 on 2020-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddriver',
            name='angle',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
