#!/bin/sh
#**********************************************************************
#* Filename    :
#* Description : a simple bash script to intialise the database and create a superuser
#* Author      : Adam Moss
#* E-mail      : adam.moss@nottingham.ac.uk
#**********************************************************************


python3 manage.py migrate
python3 manage.py createsuperuser
